# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://kyhomelab.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: KyHomelab
# Description of the Site
description: Exploring the Digital Universe - One Project at a Time
# URL of Image of the Site
site-image: /assets/images/black-hole_1171456.png
# Keywords of the Site
site-keywords: IT, homelab, cybersecurity, SOC, security operations, space enthusiast, system administration, network security, threat detection, Azure, CompTIA
# URL for the Image of custom Favicon
favicon-url: https://i.imgur.com/La7o0rG.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.imgur.com/bydrSuk.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kayjay18m@gmail.com
#facebook_username:
#twitter_username:
#instagram_username:
linkedin_username: kyle-stanley-homelab
github_username:  kyhomelab
#youtube_channel_id:
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Kyle S
# URL for the Image of the Author
author-image: /assets/images/author-astronaut-hacker.jpg
# About the Author
author-about: I'm Kyle Stanley, a Security Operations Analyst with hands-on experience in Microsoft Sentinel, threat hunting, and incident response. Currently protecting enterprise environments through proactive security monitoring, custom KQL detection engineering, and Azure security assessments. Built an advanced home lab featuring 15+ integrated security tools including Wazuh SIEM, Suricata IDS, and automated SOAR workflows. Architected a hybrid Azure honeypot that collects real-world threat intelligence and publishes community IOC feeds. Holds CompTIA Security+, Azure Administrator (AZ-104), and CompTIA A+ certificationsâ€”actively pursuing Microsoft SC-200. Passionate about turning security theory into production-ready detections, documented playbooks, and measurable risk reduction.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/kyhomelab

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
